# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 433894ad232d4569e8e9731dbaa3264520495021f1b7028beaf547fed210e8e2860ca42dc4570f3e24a64e04b1c7e40a81f50b35175f00d410a6abf48b92bd74

test:
  secret_key_base: 51e0cf8b9fa8d2f2e5a2ba63d897a08c75546dfd11fab45d7f999d36aec0b9c54e3f032b0e6b0799792014a3f994564d3f68c74bcbc2031f076958343efa9b5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
